using Tyuiu.PolyakovaAS.Sprint3.Task1.V27.Lib;
DataService ds = new DataService();
Console.WriteLine("***************************************************************************");
Console.WriteLine("* УСЛОВИЕ:                                                                *");
Console.WriteLine("* Написать программу, которая запрашивает у пользователя исходные данные, *");
Console.WriteLine("* вычисляет, и печатает результат на экране                               *");
Console.WriteLine("*                                                                         *");
Console.WriteLine("***************************************************************************");
Console.WriteLine("***************************************************************************");
Console.WriteLine("* Исходные данные                                                         *");
Console.WriteLine("***************************************************************************");
double value = 0.75;
int startValue = 1;
int stopValue = 5;
Console.WriteLine("Переменная x = " + value);
Console.WriteLine("Старт шага = " + startValue);
Console.WriteLine("Конец шага = " + stopValue);
Console.WriteLine("********************************************************************************");
Console.WriteLine("* Результат:                                                                   *");
Console.WriteLine("********************************************************************************");
Console.WriteLine("Произведение ряда = " + ds.GetMultiplySeries(value, startValue, stopValue));
Console.ReadKey();